# test_sensitive
one test of sensitive detection

- name: Gitleaks
  uses: gitleaks/gitleaks-action@v2.3.1
  

- name: TruffleHog OSS
  uses: trufflesecurity/trufflehog@v3.31.3
  
- name: ChatGPT CodeReviewer
  uses: anc95/ChatGPT-CodeReview@v1.0.4


